name: Gcovr Action
description: Generate code coverage report for C++ project using gcovr
author: Alfi Maulana
inputs:
  root:
    description: 'The root directory of your source files'
    required: false
  exclude:
    description: 'Exclude source files that match this filter'
    required: false
branding:
  color: green
  icon: terminal
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        if ! command -v gcovr &> /dev/null; then
          echo "gcovr could not be found, installing..."
          pip install gcovr
        fi
        root=${{ inputs.root }}
        exclude=${{ inputs.exclude }}
        gcovr \
          ${root:+ --root "$root"} \
          ${exclude:+ --exclude "$exclude"}
