name: test
on:
  workflow_dispatch:
  push:
jobs:
  use-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.2.0

      - name: Build and test example project
        run:  |
          cmake test -B build
          cmake --build build
          ctest --test-dir build

      - name: Use this action
        uses: ./

  use-action-from-different-root:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.2.0

      - name: Build and test example project
        working-directory: test
        run:  |
          cmake . -B build
          cmake --build build
          ctest --test-dir build

      - name: Use this action
        uses: ./
        with:
          root: test
          fail-under-line: 100

  use-action-with-exclusion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.2.0

      - name: Build and test example project
        working-directory: test
        run:  |
          cmake . -B build -DTEST_EVEN=OFF -DTEST_ODD=OFF
          cmake --build build
          ctest --test-dir build

      - name: Use this action without exclusion
        id: failed_action
        continue-on-error: true
        uses: ./
        with:
          fail-under-line: 100

      - name: Check if previous step is failing
        run: ${{ steps.failed_action.outcome == 'failure' && true || false }}

      - name: Use this action with exclusion
        uses: ./
        with:
          exclude: test/include/*
          fail-under-line: 100
